# Generated by Django 3.0.7 on 2020-06-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('bilet_id', models.AutoField(db_column='BILET_ID', primary_key=True, serialize=False)),
                ('rodzaj_biletu', models.CharField(db_column='RODZAJ_BILETU', max_length=100)),
            ],
            options={
                'db_table': 'BILET',
            },
        ),
        migrations.CreateModel(
            name='Cennik',
            fields=[
                ('cena_id', models.AutoField(db_column='CENA_ID', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(db_column='NAZWA', max_length=100)),
                ('cena', models.DecimalField(db_column='CENA', decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'CENNIK',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.AutoField(db_column='FILM_ID', primary_key=True, serialize=False)),
                ('tytul', models.CharField(db_column='TYTUL', max_length=100)),
                ('czas_trwania', models.TimeField(db_column='CZAS_TRWANIA')),
                ('ocena', models.DecimalField(blank=True, db_column='OCENA', decimal_places=2, default=0, max_digits=4, null=True)),
                ('opis', models.TextField(db_column='OPIS')),
            ],
            options={
                'db_table': 'FILM',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('klient_id', models.AutoField(db_column='KLIENT_ID', primary_key=True, serialize=False)),
                ('imie', models.CharField(db_column='IMIE', max_length=100)),
                ('nazwisko', models.CharField(db_column='NAZWISKO', max_length=100)),
                ('login', models.CharField(db_column='LOGIN', max_length=100)),
                ('email', models.CharField(db_column='EMAIL', max_length=100)),
                ('haslo', models.CharField(db_column='HASLO', max_length=100)),
            ],
            options={
                'db_table': 'KLIENT',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('produkt_id', models.AutoField(db_column='PRODUKT_ID', primary_key=True, serialize=False)),
                ('cena_id', models.IntegerField(db_column='CENA_ID')),
                ('nazwa_produktu', models.CharField(db_column='NAZWA_PRODUKTU', max_length=100)),
            ],
            options={
                'db_table': 'PRODUKT',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.AutoField(db_column='SALA_ID', primary_key=True, serialize=False)),
                ('liczba_kolumn', models.IntegerField(db_column='LICZBA_KOLUMN')),
                ('liczba_rzedow', models.IntegerField(db_column='LICZBA_RZEDOW')),
            ],
            options={
                'db_table': 'SALA',
            },
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('seans_id', models.AutoField(db_column='SEANS_ID', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, db_column='DATA', null=True)),
                ('godzina', models.TimeField(db_column='GODZINA')),
                ('film', models.ForeignKey(db_column='FILM_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Film')),
                ('sala', models.ForeignKey(db_column='SALA_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Sala')),
            ],
            options={
                'db_table': 'SEANS',
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('zamowienie_id', models.AutoField(db_column='ZAMOWIENIE_ID', primary_key=True, serialize=False)),
                ('do_zaplaty', models.DecimalField(db_column='DO_ZAPLATY', decimal_places=2, max_digits=4)),
                ('bilet', models.ForeignKey(blank=True, db_column='BILET_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Bilet')),
                ('klient', models.ForeignKey(db_column='KLIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Klient')),
                ('produkt', models.ForeignKey(blank=True, db_column='PRODUKT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Produkt')),
            ],
            options={
                'db_table': 'ZAMOWIENIE',
            },
        ),
        migrations.CreateModel(
            name='ZajeteMiejsca',
            fields=[
                ('miejsce_id', models.AutoField(db_column='MIEJSCE_ID', primary_key=True, serialize=False)),
                ('adres_miejsca', models.CharField(db_column='ADRES_MIEJSCA', max_length=10)),
                ('seans', models.ForeignKey(db_column='SEANS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Seans')),
            ],
            options={
                'db_table': 'ZAJETE_MIEJSCA',
            },
        ),
        migrations.AddField(
            model_name='bilet',
            name='cena',
            field=models.ForeignKey(db_column='CENA_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Cennik'),
        ),
        migrations.AddField(
            model_name='bilet',
            name='seans',
            field=models.ForeignKey(blank=True, db_column='SEANS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Seans'),
        ),
    ]
